/** Generated by scripts/generate-tokens.ts from DESIGN.md. Do not edit. */

export const noruxTokens = {
  "colors": {
    "amber-100": "#FFF4D6",
    "amber-300": "#F2C76D",
    "amber-700": "#8A5A00",
    "amber-950": "#44320F",
    "blue-100": "#E8F2FB",
    "blue-150": "#CFE4F7",
    "blue-300": "#A8CFF5",
    "blue-400": "#82C0F5",
    "blue-500": "#4A8DE0",
    "blue-600": "#73B6F2",
    "blue-700": "#2F6FA7",
    "blue-800": "#245B8B",
    "blue-850": "#245579",
    "blue-900": "#18364D",
    "blue-950": "#10202D",
    "green-100": "#E6F7EC",
    "green-400": "#6DD89B",
    "green-700": "#20744A",
    "green-950": "#123D27",
    "ink": "#1D252C",
    "neutral-0": "#FFFFFF",
    "neutral-100": "#EDF2F6",
    "neutral-150": "#E8EDF1",
    "neutral-200": "#DCE2E6",
    "neutral-300": "#9DA9B2",
    "neutral-400": "#84919A",
    "neutral-50": "#F7F7F4",
    "neutral-500": "#65727C",
    "neutral-600": "#53616A",
    "neutral-700": "#2B343B",
    "neutral-800": "#20282E",
    "neutral-900": "#181E22",
    "neutral-950": "#121619",
    "neutral-975": "#0E1419",
    "red-100": "#FBEAEC",
    "red-300": "#F29BA5",
    "red-700": "#A42D3A",
    "red-950": "#481F27"
  },
  "norux": {
    "border": {
      "width": "1px"
    },
    "focus": {
      "offset": "3px",
      "width": "3px"
    },
    "font": {
      "mono": "ui-monospace, 'SFMono-Regular', 'Cascadia Code', Consolas, monospace",
      "sans": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif"
    },
    "layer": {
      "base": 0,
      "modal": 200,
      "progress": 40,
      "skip-link": 100,
      "sticky": 30
    },
    "motion": {
      "duration": {
        "fast": "120ms",
        "slow": "240ms",
        "standard": "160ms"
      },
      "easing": {
        "standard": "ease-out"
      }
    },
    "shadow": {
      "none": "none",
      "overlay": "0 24px 80px rgb(0 0 0 / 24%)"
    },
    "size": {
      "article-max": "720px",
      "control-compact": "36px",
      "control-touch": "44px",
      "header": "64px",
      "page-max": "1180px",
      "reading-measure": "72ch"
    },
    "themes": {
      "dark": {
        "color": {
          "action": {
            "on-primary": "#10202D",
            "period": "#4A8DE0",
            "primary": "#82C0F5",
            "primary-active": "#73B6F2",
            "primary-hover": "#A8CFF5",
            "soft": "#18364D"
          },
          "background": {
            "canvas": "#121619",
            "code": "#0E1419",
            "sunken": "#0E1419",
            "surface": "#181E22"
          },
          "border": {
            "strong": "#65727C",
            "subtle": "#2B343B"
          },
          "feedback": {
            "negative": "#F29BA5",
            "negative-soft": "#481F27",
            "positive": "#6DD89B",
            "positive-soft": "#123D27",
            "warning": "#F2C76D",
            "warning-soft": "#44320F"
          },
          "focus": {
            "ring": "#82C0F5"
          },
          "foreground": {
            "inverse": "#121619",
            "muted": "#9DA9B2",
            "primary": "#E8EDF1"
          },
          "selection": "#245579"
        }
      },
      "light": {
        "color": {
          "action": {
            "on-primary": "#FFFFFF",
            "period": "#4A8DE0",
            "primary": "#2F6FA7",
            "primary-active": "#18364D",
            "primary-hover": "#245B8B",
            "soft": "#E8F2FB"
          },
          "background": {
            "canvas": "#F7F7F4",
            "code": "#EDF2F6",
            "sunken": "#EDF2F6",
            "surface": "#FFFFFF"
          },
          "border": {
            "strong": "#84919A",
            "subtle": "#DCE2E6"
          },
          "feedback": {
            "negative": "#A42D3A",
            "negative-soft": "#FBEAEC",
            "positive": "#20744A",
            "positive-soft": "#E6F7EC",
            "warning": "#8A5A00",
            "warning-soft": "#FFF4D6"
          },
          "focus": {
            "ring": "#2F6FA7"
          },
          "foreground": {
            "inverse": "#FFFFFF",
            "muted": "#65727C",
            "primary": "#1D252C"
          },
          "selection": "#CFE4F7"
        }
      }
    }
  },
  "radius": {
    "full": "9999px",
    "lg": "12px",
    "md": "8px",
    "none": "0px",
    "sm": "4px"
  },
  "spacing": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "24px",
    "6": "32px",
    "7": "48px",
    "8": "72px",
    "control-touch": "44px"
  },
  "typography": {
    "body-lg": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "18px",
      "fontWeight": 400,
      "letterSpacing": "-0.01em",
      "lineHeight": 1.82
    },
    "body-md": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.6
    },
    "code-md": {
      "fontFamily": "ui-monospace, 'SFMono-Regular', 'Cascadia Code', Consolas, monospace",
      "fontSize": "14px",
      "fontWeight": 400,
      "lineHeight": 1.6
    },
    "display-lg": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "56px",
      "fontWeight": 760,
      "letterSpacing": "-0.045em",
      "lineHeight": 1.12
    },
    "display-md": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "42px",
      "fontWeight": 760,
      "letterSpacing": "-0.04em",
      "lineHeight": 1.08
    },
    "heading-lg": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "30px",
      "fontWeight": 700,
      "letterSpacing": "-0.035em",
      "lineHeight": 1.35
    },
    "heading-md": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "24px",
      "fontWeight": 700,
      "letterSpacing": "-0.025em",
      "lineHeight": 1.4
    },
    "label-md": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "14px",
      "fontWeight": 600,
      "lineHeight": 1.45
    },
    "label-sm": {
      "fontFamily": "'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif",
      "fontSize": "12px",
      "fontWeight": 650,
      "letterSpacing": "0.02em",
      "lineHeight": 1.4
    }
  }
} as const;

export type NoruxTheme = keyof typeof noruxTokens.norux.themes;
export type NoruxTokens = typeof noruxTokens;
