import { asMap, flatten, readDesignSource, resolveReferences, sortMap, toKebab, type DesignMap, type DesignValue } from "./design-source.ts";

const generated = "Generated by scripts/generate-tokens.ts from DESIGN.md. Do not edit.";

type TokenArtifacts = {
  css: string;
  dtcg: string;
  typescript: string;
};

export async function createTokenArtifacts(): Promise<TokenArtifacts> {
  const source = await readDesignSource();
  const resolved = resolveReferences(source, source);
  const root = asMap(resolved, "DESIGN.md frontmatter");
  const norux = asMap(root.norux, "norux");
  const themes = asMap(norux.themes, "norux.themes");

  return {
    css: createCss(root, norux, themes),
    dtcg: createDtcg(root, norux, themes),
    typescript: createTypeScript(root, norux)
  };
}

function createCss(root: DesignMap, norux: DesignMap, themes: DesignMap) {
  const common = [
    ...renameGroup(asMap(root.spacing, "spacing"), ["space"]),
    ...renameGroup(asMap(root.rounded, "rounded"), ["radius"]),
    ...renameGroup(asMap(root.typography, "typography"), ["typography"]),
    ...renameGroup(omit(norux, ["themes", "accessibility", "source"]), [])
  ];
  const light = themeVariables(asMap(themes.light, "norux.themes.light"));
  const dark = themeVariables(asMap(themes.dark, "norux.themes.dark"));

  return [
    `/* ${generated} */`,
    ":root {",
    "  color-scheme: light;",
    ...renderVariables(common),
    "}",
    "",
    ':root, :root[data-theme="light"] {',
    "  color-scheme: light;",
    ...renderVariables(light),
    "}",
    "",
    ':root[data-theme="dark"] {',
    "  color-scheme: dark;",
    ...renderVariables(dark),
    "}",
    ""
  ].join("\n");
}

function createDtcg(root: DesignMap, norux: DesignMap, themes: DesignMap) {
  const colors = asMap(root.colors, "colors");
  const typography = asMap(root.typography, "typography");
  const spacing = asMap(root.spacing, "spacing");
  const rounded = asMap(root.rounded, "rounded");

  const output = {
    $description: "Generated from DESIGN.md. Do not edit.",
    color: {
      palette: dtcgTree(colors, "color"),
      theme: {
        light: dtcgTree(asMap(themes.light, "norux.themes.light").color as DesignMap, "color"),
        dark: dtcgTree(asMap(themes.dark, "norux.themes.dark").color as DesignMap, "color")
      }
    },
    dimension: {
      space: dtcgTree(spacing, "dimension"),
      radius: dtcgTree(rounded, "dimension"),
      size: dtcgTree(asMap(norux.size, "norux.size"), "dimension"),
      border: dtcgTree(asMap(norux.border, "norux.border"), "dimension"),
      focus: dtcgTree(asMap(norux.focus, "norux.focus"), "dimension")
    },
    duration: dtcgTree(asMap(asMap(norux.motion, "norux.motion").duration, "norux.motion.duration"), "duration"),
    fontFamily: dtcgTree(asMap(norux.font, "norux.font"), "fontFamily"),
    fontWeight: dtcgTypography(typography, "fontWeight"),
    typography: dtcgTypography(typography, "typography"),
    shadow: dtcgTree(asMap(norux.shadow, "norux.shadow"), "shadow"),
    number: dtcgTree(asMap(norux.layer, "norux.layer"), "number")
  };

  return `${JSON.stringify(sortMap(output), null, 2)}\n`;
}

function createTypeScript(root: DesignMap, norux: DesignMap) {
  const tokens = {
    colors: root.colors,
    typography: root.typography,
    spacing: root.spacing,
    radius: root.rounded,
    norux: omit(norux, ["accessibility", "source"])
  };

  return [
    `/** ${generated} */`,
    "",
    `export const noruxTokens = ${JSON.stringify(sortMap(tokens), null, 2)} as const;`,
    "",
    "export type NoruxTheme = keyof typeof noruxTokens.norux.themes;",
    "export type NoruxTokens = typeof noruxTokens;",
    ""
  ].join("\n");
}

function renameGroup(group: DesignMap, prefix: string[]) {
  return flatten(group).map(({ path, value }) => ({ path: prefix.concat(path), value }));
}

function themeVariables(theme: DesignMap) {
  const color = asMap(theme.color, "theme.color");
  return flatten(color).map(({ path, value }) => ({ path: ["color", ...path], value }));
}

function renderVariables(values: Array<{ path: string[]; value: string | number | boolean }>) {
  return values
    .sort((left, right) => left.path.join(".").localeCompare(right.path.join(".")))
    .map(({ path, value }) => `  --norux-${path.map(toKebab).join("-")}: ${value};`);
}

function omit(source: DesignMap, keys: string[]) {
  return Object.fromEntries(Object.entries(source).filter(([key]) => !keys.includes(key)));
}

function dtcgTree(value: DesignValue, type: string): DesignValue {
  if (!isLeaf(value)) {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, dtcgTree(item, type)]));
  }

  return { $type: type, $value: value };
}

function dtcgTypography(typography: DesignMap, type: "fontWeight" | "typography") {
  return Object.fromEntries(
    Object.entries(typography).map(([key, value]) => {
      const token = asMap(value, `typography.${key}`);
      if (type === "fontWeight") return [key, { $type: "fontWeight", $value: token.fontWeight }];
      return [key, { $type: "typography", $value: token }];
    })
  );
}

function isLeaf(value: DesignValue): value is string | number | boolean {
  return !Array.isArray(value) && (typeof value !== "object" || value === null);
}
